ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: code2.k3s-fch.dev.gnc
      paths:
        - /
  annotations:
    cert-manager.io/cluster-issuer: "ca-issuer"
    traefik.ingress.kubernetes.io/router.middlewares: default-oauth2-proxy-forward@kubernetescrd
  tls:
    - hosts:
        - code2.k3s-fch.dev.gnc
      secretName: code2-k3s-fch-dev-gnc
  
extraVars:
  - name: TZ
    value: Pacific/Noumea
  - name: HTTP_PROXY
    value: http://proxy-web.proxy-dmz.gnc:3128
  - name: HTTPS_PROXY
    value: http://proxy-web.proxy-dmz.gnc:3128
  - name: NO_PROXY
    value: 127.0.0.0/24,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,0.0.0.0/32,localhost,.svc,.recif.nc,.appli-gestion.nc,.gnc,.valid-gouv.nc,.dmz.nc,.admin.nc,jira.gouv.nc,jira-info.gouv.nc,10.96.0.1
  - name: PASSWORD
    value: k3sfch

persistence:
  enabled: false