kind: ConfigMap
apiVersion: v1
metadata:
  name: servers-config
data:
  servers.json: |-
    {
      "Servers": {
        "1": {
          "Name": "ma_bdd",
          "Group": "Servers",
          "Host": "ma_bdd",
          "Port": 5432,
          "MaintenanceDB": "raven",
          "Username": "raven",
          "SSLMode": "prefer"
        }
      }
    }