global:
  image:
    repository: docker-registry.ref.gnc/argoproj/argocd

argo-cd:
  fullnameOverride: "argocd"
  namespace: argocd
  configs:
    repositories:
      k3s-fch:
        url: https://github.com/BlueNc/k3s-fch.git
    params:
      server.insecure: true
  crds:
    install: true
    keep: false
  repoServer:
    env:
      - name: HTTP_PROXY
        value: http://proxy-web.proxy-dmz.gnc:3128
      - name: HTTPS_PROXY
        value: http://proxy-web.proxy-dmz.gnc:3128
      - name: NO_PROXY
        value: 127.0.0.0/24,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,0.0.0.0/32,localhost,.svc
  dex:
    enabled: false
  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - argo-cd.k3s-fch.dev.gnc
      annotations:
        cert-manager.io/issuer: "ca-issuer"
      tls:
        - hosts:
            - argo-cd.k3s-fch.dev.gnc
          secretName: k3s-fch-dev-gnc
      https: false
