apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: code-server
    server: https://kubernetes.default.svc
  project: argocd
  source:
    path: code-server/manifests
    repoURL: https://github.com/BlueNc/k3s-fch.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
