apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: code-server
    server: https://kubernetes.default.svc
  project: argocd
  source:
    repoURL: https://github.com/BlueNc/code-server
    targetRevision: HEAD
    path: ci/helm-chart
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/BlueNc/k3s-fch/main/code-server/values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true