apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dbgate
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dbgate
    server: https://kubernetes.default.svc
  project: argocd
  source:
    path: dbgate
    repoURL: https://github.com/BlueNc/k3s-fch.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true