apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin4
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: pgadmin4
    server: https://kubernetes.default.svc
  project: argocd
  source:
    repoURL: https://helm.runix.net/
    chart: pgadmin4
    targetRevision: 1.13.9
    helm:
      values: |
        image:
          registry: docker-registry.ref.gnc
        ingress:
          enabled: true
          ingressClassName: traefik
          hosts:
            - host: pgadmin.k3s-fch.dev.gnc
              paths:
                - path: /
                  pathType: Prefix
          annotations:
            cert-manager.io/issuer: "ca-issuer"
          tls:
            - hosts:
                - pgadmin.k3s-fch.dev.gnc
              secretName: k3s-fch-dev-gnc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true