apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secret
  namespace: argocd
spec:
  destination:
    namespace: sealed-secret
    server: https://kubernetes.default.svc
  project: argocd
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets/
    targetRevision: 2.7.2
    chart: sealed-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true