apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-generator
  namespace: argocd
spec:
  destination:
    namespace: secret-generator
    server: https://kubernetes.default.svc
  project: argocd
  source:
    repoURL: https://helm.mittwald.de
    targetRevision: 3.4.0
    chart: kubernetes-secret-generator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true