apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sysbox
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: argocd
  source:
    path: sysbox-k8s-manifests/
    repoURL: https://github.com/nestybox/sysbox.git
    targetRevision: HEAD
    directory:
      include: sysbox-install.yaml
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
