kind: ConfigMap
apiVersion: v1
metadata:
  name: code-server-settings
data:
  settings.json: |-
    {
        "workbench.colorTheme": "Default Dark+",
        "terminal.integrated.rightClickBehavior": "default",
        "terminal.integrated.copyOnSelection": true,
        "redhat.telemetry.enabled": false,
        "vs-kubernetes": {
            "vscode-kubernetes.kubectl-path.linux": "/home/coder/.local/state/vs-kubernetes/tools/kubectl/kubectl",
            "vscode-kubernetes.minikube-path.linux": "/home/coder/.local/state/vs-kubernetes/tools/minikube/linux-amd64/minikube",
            "vscode-kubernetes.helm-path.linux": "/home/coder/.local/state/vs-kubernetes/tools/helm/linux-amd64/helm",
            "vs-kubernetes.minikube-show-information-expiration": "2022-12-31T03:03:23.872Z"
        },

        "editor.renderWhitespace": "all",
        "editor.autoClosingBrackets": "never",
        "editor.autoClosingQuotes": "never",
        "extensions.ignoreRecommendations": true,
        "workbench.editor.enablePreviewFromQuickOpen": false,
        "workbench.editor.enablePreview": false,
        "workbench.list.openMode": "doubleClick",
        "typescript.updateImportsOnFileMove.enabled": "always",
        "html.autoClosingTags": false,
        "javascript.preferences.quoteStyle": "single",
        "typescript.preferences.quoteStyle": "single",
        "workbench.startupEditor": "readme",
        "files.autoSave": "off",
        "terminal.integrated.tabs.enabled": true,
        "redhat.telemetry.enabled": false,
        "editor.minimap.enabled": false,
        "editor.hover.delay": 1000
    }
  keybindings.json: |-
    [
      {
          "key": "[Backquote]",
          "command": "workbench.action.terminal.toggleTerminal"
      },
      {
          "key": "ctrl+alt+q",
          "command": "workbench.action.quit"
      },
      {
          "key": "ctrl+q",
          "command": "-workbench.action.quit"
      },
      {
          "key": "backspace alt",
          "command": "jupyter.runcurrentcellandaddbelow",
          "when": "editorTextFocus && jupyter.featureenabled && jupyter.hascodecells && !editorHasSelection"
      },
      {
          "key": "alt+enter",
          "command": "-jupyter.runcurrentcellandaddbelow",
          "when": "editorTextFocus && jupyter.featureenabled && jupyter.hascodecells && !editorHasSelection"
      },
      {
          "key": "alt+enter",
          "command": "editor.action.quickFix",
          "when": "editorHasCodeActionsProvider && editorTextFocus && !editorReadonly"
      },
      {
          "key": "ctrl+shift+[Comma]",
          "command": "-editor.action.quickFix",
          "when": "editorHasCodeActionsProvider && editorTextFocus && !editorReadonly"
      },
      {
          "key": "alt+right",
          "command": "editor.action.addSelectionToNextFindMatch",
          "when": "editorFocus"
      },
      {
          "key": "ctrl+d",
          "command": "-editor.action.addSelectionToNextFindMatch",
          "when": "editorFocus"
      },
      {
          "key": "ctrl+d",
          "command": "editor.action.deleteLines",
          "when": "textInputFocus && !editorReadonly"
      },
      {
          "key": "ctrl+shift+k",
          "command": "-editor.action.deleteLines",
          "when": "textInputFocus && !editorReadonly"
      },
      {
          "key": "alt+right",
          "command": "-workbench.action.terminal.focusNextPane",
          "when": "terminalFocus"
      },
      {
          "key": "alt+right",
          "command": "-gitlens.key.alt+right",
          "when": "gitlens:key:alt+right"
      },
      {
          "key": "shift+f4",
          "command": "-search.action.focusPreviousSearchResult",
          "when": "hasSearchResult"
      },
      {
          "key": "shift+f4",
          "command": "-goToPreviousReference",
          "when": "referenceSearchVisible"
      },
      {
          "key": "shift+f4",
          "command": "-goToPreviousReferenceFromEmbeddedEditor",
          "when": "inReferenceSearchEditor"
      },
      {
          "key": "shift+f4",
          "command": "-references-view.prev",
          "when": "reference-list.hasResult"
      },
      {
          "key": "shift+f4",
          "command": "references-view.find",
          "when": "editorHasReferenceProvider"
      },
      {
          "key": "shift+alt+f12",
          "command": "-references-view.find",
          "when": "editorHasReferenceProvider"
      },
      {
          "key": "alt+left",
          "command": "-workbench.action.terminal.focusPreviousPane",
          "when": "terminalFocus"
      },
      {
          "key": "alt+left",
          "command": "-gitlens.key.alt+left",
          "when": "gitlens:key:alt+left"
      },
      {
          "key": "alt+left",
          "command": "editor.action.addSelectionToPreviousFindMatch"
      },
      {
          "key": "shift+[Backquote]",
          "command": "workbench.action.toggleMaximizedPanel"
      }
    ]