postgresql:
  auth:
    existingSecret: postgres
    username: coder
    database: coder

coder:
  coder:
    env:
      - name: PG_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres
            key: password
      - name: CODER_PG_CONNECTION_URL
        value: postgres://coder:$(PG_PASSWORD)@postgres:5432/coder?sslmode=disable
    ingress:
      enable: true
      ingressClassName: traefik
      host: coder.k3s-fch.dev.gnc
      wildcardHost: "*.coder.k3s-fch.dev.gnc"
      annotations:
        cert-manager.io/cluster-issuer: "ca-issuer"
        traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd,default-oauth2-proxy-redirect@kubernetescrd,default-oauth2-proxy-forward@kubernetescrd
      tls:
        enable: true
        secretName: coder-k3s-fch-dev-gnc
        wildcardSecretName: wildcard-coder-k3s-fch-dev-gnc
